//! ★v24.33 键盘快捷连发卡片: 用户的 键盘.svg 解析重制 (双主题配色 + 可点击键位表)。
//!
//! 交互: 点键盘上的按键选中 (可多选) → 「确认修改连发」一次性生效 = 添加勾选键的
//! **同名映射** (S→S) + 移除标红的键。已在连发映射里的同名键标绿, 点击绿键 = **标记
//! 移除** (再点取消, 确认后才真删); 触发键已存在但目标不同 (S→X) → 确认时提示是否覆盖。

use crate::config::{AppConfig, KeyMapping};
use crate::gui::SorahkGui;
use crate::gui::theme::Theme;
use eframe::egui;
/// 键盘 SVG viewBox (resources/keyboard[-light].svg 同源)
pub const VIEWBOX: (f32, f32) = (1120.0, 420.0);
const RENDER_SCALE: f32 = 2.0;

pub struct KeyboardKey {
    /// 本软件键名 (与 state::key_name_to_vk 词表互逆)
    pub name: &'static str,
    /// SVG 上的显示文本
    pub label: &'static str,
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

/// 键位表 (viewBox 坐标, 与 SVG 几何 1:1 同源生成)
pub static KEYS: &[KeyboardKey] = &[
/* GENERATED by work/_gen_keyboard.py — 键位表与 keyboard.svg 同源 */
    KeyboardKey { name: "ESC", label: "Esc", x: 30.0, y: 30.0, w: 50.0, h: 40.0 },
    KeyboardKey { name: "OEM_3", label: "~", x: 30.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "TAB", label: "Tab", x: 30.0, y: 150.0, w: 60.0, h: 45.0 },
    KeyboardKey { name: "CAPSLOCK", label: "CapsLk", x: 30.0, y: 200.0, w: 75.0, h: 45.0 },
    KeyboardKey { name: "LSHIFT", label: "LShift", x: 30.0, y: 250.0, w: 95.0, h: 45.0 },
    KeyboardKey { name: "LCTRL", label: "LCtrl", x: 30.0, y: 300.0, w: 50.0, h: 45.0 },
    KeyboardKey { name: "1", label: "1", x: 75.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "LWIN", label: "LWin", x: 85.0, y: 300.0, w: 50.0, h: 45.0 },
    KeyboardKey { name: "F1", label: "F1", x: 90.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "Q", label: "Q", x: 95.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "A", label: "A", x: 110.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "2", label: "2", x: 120.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "Z", label: "Z", x: 130.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F2", label: "F2", x: 135.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "W", label: "W", x: 140.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "LALT", label: "LAlt", x: 140.0, y: 300.0, w: 50.0, h: 45.0 },
    KeyboardKey { name: "S", label: "S", x: 155.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "3", label: "3", x: 165.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "X", label: "X", x: 175.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F3", label: "F3", x: 180.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "E", label: "E", x: 185.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "SPACE", label: "Space", x: 195.0, y: 300.0, w: 260.0, h: 45.0 },
    KeyboardKey { name: "D", label: "D", x: 200.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "4", label: "4", x: 210.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "C", label: "C", x: 220.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F4", label: "F4", x: 225.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "R", label: "R", x: 230.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F", label: "F", x: 245.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "5", label: "5", x: 255.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "V", label: "V", x: 265.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "T", label: "T", x: 275.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F5", label: "F5", x: 285.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "G", label: "G", x: 290.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "6", label: "6", x: 300.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "B", label: "B", x: 310.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "Y", label: "Y", x: 320.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F6", label: "F6", x: 330.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "H", label: "H", x: 335.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "7", label: "7", x: 345.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "N", label: "N", x: 355.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "U", label: "U", x: 365.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F7", label: "F7", x: 375.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "J", label: "J", x: 380.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "8", label: "8", x: 390.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "M", label: "M", x: 400.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "I", label: "I", x: 410.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F8", label: "F8", x: 420.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "K", label: "K", x: 425.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "9", label: "9", x: 435.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "OEM_COMMA", label: ",", x: 445.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "O", label: "O", x: 455.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "RALT", label: "RAlt", x: 460.0, y: 300.0, w: 50.0, h: 45.0 },
    KeyboardKey { name: "L", label: "L", x: 470.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F9", label: "F9", x: 480.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "0", label: "0", x: 480.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "OEM_PERIOD", label: ".", x: 490.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "P", label: "P", x: 500.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "OEM_1", label: ";", x: 515.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "RWIN", label: "RWin", x: 515.0, y: 300.0, w: 50.0, h: 45.0 },
    KeyboardKey { name: "F10", label: "F10", x: 525.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "OEM_MINUS", label: "-", x: 525.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "OEM_2", label: "/", x: 535.0, y: 250.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "OEM_4", label: "[", x: 545.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "OEM_7", label: "'", x: 560.0, y: 200.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "F11", label: "F11", x: 570.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "OEM_PLUS", label: "=", x: 570.0, y: 100.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "RSHIFT", label: "RShift", x: 580.0, y: 250.0, w: 115.0, h: 45.0 },
    KeyboardKey { name: "OEM_6", label: "]", x: 590.0, y: 150.0, w: 40.0, h: 45.0 },
    KeyboardKey { name: "ENTER", label: "Enter", x: 605.0, y: 200.0, w: 90.0, h: 45.0 },
    KeyboardKey { name: "F12", label: "F12", x: 615.0, y: 30.0, w: 40.0, h: 40.0 },
    KeyboardKey { name: "BACKSPACE", label: "←BS", x: 615.0, y: 100.0, w: 80.0, h: 45.0 },
    KeyboardKey { name: "RCTRL", label: "RCtrl", x: 625.0, y: 300.0, w: 70.0, h: 45.0 },
    KeyboardKey { name: "OEM_5", label: "\\", x: 635.0, y: 150.0, w: 60.0, h: 45.0 },
    KeyboardKey { name: "SNAPSHOT", label: "Print", x: 685.0, y: 30.0, w: 60.0, h: 40.0 },
    KeyboardKey { name: "INSERT", label: "Ins", x: 720.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "DELETE", label: "Del", x: 720.0, y: 150.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "LEFT", label: "←", x: 720.0, y: 300.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "SCROLL", label: "Scroll", x: 755.0, y: 30.0, w: 60.0, h: 40.0 },
    KeyboardKey { name: "HOME", label: "Home", x: 770.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "END", label: "End", x: 770.0, y: 150.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "UP", label: "↑", x: 770.0, y: 250.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "DOWN", label: "↓", x: 770.0, y: 300.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "PAGEUP", label: "PgUp", x: 820.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "PAGEDOWN", label: "PgDn", x: 820.0, y: 150.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "RIGHT", label: "→", x: 820.0, y: 300.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "PAUSE", label: "Pause", x: 825.0, y: 30.0, w: 60.0, h: 40.0 },
    KeyboardKey { name: "NUMLOCK", label: "Num", x: 880.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD7", label: "7", x: 880.0, y: 150.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD4", label: "4", x: 880.0, y: 200.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD1", label: "1", x: 880.0, y: 250.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD0", label: "0", x: 880.0, y: 300.0, w: 95.0, h: 45.0 },
    KeyboardKey { name: "DIVIDE", label: "/", x: 930.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD8", label: "8", x: 930.0, y: 150.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD5", label: "5", x: 930.0, y: 200.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD2", label: "2", x: 930.0, y: 250.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "MULTIPLY", label: "*", x: 980.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD9", label: "9", x: 980.0, y: 150.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD6", label: "6", x: 980.0, y: 200.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "NUMPAD3", label: "3", x: 980.0, y: 250.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "DECIMAL", label: ".", x: 980.0, y: 300.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "SUBTRACT", label: "-", x: 1030.0, y: 100.0, w: 45.0, h: 45.0 },
    KeyboardKey { name: "ADD", label: "+", x: 1030.0, y: 150.0, w: 45.0, h: 95.0 },
];

/// 某键在当前连发映射中的占用状态
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum KeyMapState {
    /// 空闲: 可直接添加同名连发
    Free,
    /// 已存在同名映射 S→S (标绿, 不可重选)
    SameName,
    /// 触发键已存在但目标不同 (S→X): 确认时提示覆盖
    OtherTarget,
}

fn key_map_state(config: &crate::config::AppConfig, name: &str) -> KeyMapState {
    for m in &config.mappings {
        if m.trigger_key.eq_ignore_ascii_case(name) {
            let same = m.target_keys.len() == 1 && m.target_keys[0].eq_ignore_ascii_case(name);
            return if same { KeyMapState::SameName } else { KeyMapState::OtherTarget };
        }
    }
    KeyMapState::Free
}

/// 使用 resvg 渲染键盘 SVG 为 egui 纹理 (2x 超采样, 双主题变体)。
pub fn load_keyboard_texture(ctx: &egui::Context, dark: bool) -> Option<egui::TextureHandle> {
    let svg_data: &[u8] = if dark {
        include_bytes!("../../resources/keyboard.svg")
    } else {
        include_bytes!("../../resources/keyboard-light.svg")
    };

    let mut opt = resvg::usvg::Options::default();
    opt.fontdb_mut().load_system_fonts();
    let tree = resvg::usvg::Tree::from_data(svg_data, &opt).ok()?;

    let size = tree.size().to_int_size();
    let width = (size.width() as f32 * RENDER_SCALE) as u32;
    let height = (size.height() as f32 * RENDER_SCALE) as u32;
    let mut pixmap = resvg::tiny_skia::Pixmap::new(width, height)?;
    let transform = resvg::tiny_skia::Transform::from_scale(RENDER_SCALE, RENDER_SCALE);
    resvg::render(&tree, transform, &mut pixmap.as_mut());

    let image_size = [pixmap.width() as usize, pixmap.height() as usize];
    let color_image = egui::ColorImage::from_rgba_unmultiplied(image_size, pixmap.data());
    Some(ctx.load_texture(
        if dark { "keyboard_svg_dark" } else { "keyboard_svg_light" },
        color_image,
        egui::TextureOptions::LINEAR,
    ))
}

impl SorahkGui {
    /// ★v24.33 「键盘快捷连发」卡片 (连发页: 预设管理下方 / 连发映射上方)。
    pub(crate) fn render_keyboard_quick_card(&mut self, ui: &mut egui::Ui, ctx: &egui::Context) {
        let th = Theme::new(self.dark_mode);

        // 主题切换时重渲染 (按 dark 标记缓存)
        if self.keyboard_texture.is_none() || self.keyboard_texture_dark != self.dark_mode {
            self.keyboard_texture = load_keyboard_texture(ctx, self.dark_mode);
            self.keyboard_texture_dark = self.dark_mode;
        }

        egui::CollapsingHeader::new(
            egui::RichText::new("⌨ 键盘 (点按键 = 批量添加同名连发)").size(15.0),
        )
        .id_source("keyboard_quick_card")
        .default_open(true)
        .show(ui, |ui| {
            th.card(ui, None, |ui| {
                ui.label(th.hint_text(
                    "点键盘上的按键选中 (可多选) → 「确认修改连发」一次性生效: 添加已选键的同名连发 (如 S→S) + 移除标红键。\n                     已存在的同名映射标绿, 点击绿键 = 标记移除 (再点取消, 确认后才真删); 触发键已被其他映射占用 (如 S→X) 时, 确认会提示是否覆盖。",
                ));
                ui.add_space(8.0);

                /* 键盘图: 宽度铺满可用区, 高度按 viewBox 比例 */
                let display_w = ui.available_width().min(1100.0);
                let display_h = display_w * (VIEWBOX.1 / VIEWBOX.0);
                let (rect, _) =
                    ui.allocate_exact_size(egui::vec2(display_w, display_h), egui::Sense::hover());
                let painter = ui.painter();

                if let Some(texture) = &self.keyboard_texture {
                    painter.image(
                        texture.id(),
                        rect,
                        egui::Rect::from_min_max(egui::pos2(0.0, 0.0), egui::pos2(1.0, 1.0)),
                        egui::Color32::WHITE,
                    );
                } else {
                    painter.text(
                        rect.center(),
                        egui::Align2::CENTER_CENTER,
                        "键盘图片加载失败",
                        egui::FontId::proportional(14.0),
                        th.hint,
                    );
                }

                /* 每个键: 状态描边覆盖层 + 点击切换选中 */
                for key in KEYS {
                    let krect = egui::Rect::from_min_size(
                        egui::pos2(
                            rect.min.x + key.x / VIEWBOX.0 * rect.width(),
                            rect.min.y + key.y / VIEWBOX.1 * rect.height(),
                        ),
                        egui::vec2(key.w / VIEWBOX.0 * rect.width(), key.h / VIEWBOX.1 * rect.height()),
                    );
                    let state = key_map_state(&self.config, key.name);
                    let selected = self
                        .kbd_selected
                        .iter()
                        .any(|s| s.eq_ignore_ascii_case(key.name));
                    let marked_remove = self
                        .kbd_removals
                        .iter()
                        .any(|s| s.eq_ignore_ascii_case(key.name));

                    /* 覆盖层: 选中 = 靛蓝; 待移除 = 红; 已连发 = 绿描边; 占用 = 琥珀描边 */
                    if marked_remove {
                        painter.rect_filled(krect, 4, th.bad_soft);
                    } else if selected {
                        painter.rect_filled(krect, 4, th.accent_soft);
                    } else if state == KeyMapState::SameName {
                        painter.rect_filled(
                            krect,
                            4,
                            egui::Color32::from_rgba_unmultiplied(52, 211, 153, 26),
                        );
                    }
                    let stroke = if marked_remove {
                        egui::Stroke::new(2.0, th.bad)
                    } else if selected {
                        egui::Stroke::new(2.0, th.accent)
                    } else if state == KeyMapState::SameName {
                        egui::Stroke::new(1.8, th.good)
                    } else if state == KeyMapState::OtherTarget {
                        egui::Stroke::new(1.5, th.warn)
                    } else {
                        egui::Stroke::NONE
                    };
                    if stroke.width > 0.0 {
                        painter.rect_stroke(krect, 4, stroke, egui::StrokeKind::Inside);
                    }

                    let id = ui.id().with("kbd_key").with(key.name);
                    let resp = ui.interact(krect, id, egui::Sense::click());
                    if resp.hovered() {
                        ui.ctx().set_cursor_icon(egui::CursorIcon::PointingHand);
                    }

                    let hover = if marked_remove {
                        format!(
                            "{} — 将移除 (确认后生效), 再次点击取消",
                            key.label
                        )
                    } else {
                        match state {
                            KeyMapState::SameName => format!(
                                "{} — 已有同名连发 ({}→{}), 点击标记移除 (确认后生效)",
                                key.label, key.name, key.name
                            ),
                            KeyMapState::OtherTarget => format!(
                                "{} — 已被其他映射占用 (确认时可选择覆盖)",
                                key.label
                            ),
                            KeyMapState::Free => {
                                if selected {
                                    format!("{} — 已选中 (点击取消)", key.label)
                                } else {
                                    format!(
                                        "{} — 点击选中 (将添加 {}→{} 连发)",
                                        key.label, key.name, key.name
                                    )
                                }
                            }
                        }
                    };

                    if resp.clicked() && state == KeyMapState::SameName {
                        /* ★绿键: 切换移除标记 (点「确认修改连发」才真正删除) */
                        if marked_remove {
                            self.kbd_removals
                                .retain(|s| !s.eq_ignore_ascii_case(key.name));
                        } else {
                            self.kbd_removals.push(key.name.to_string());
                        }
                    } else if resp.clicked() {
                        /* 其余键: 切换选中 */
                        if selected {
                            self.kbd_selected
                                .retain(|s| !s.eq_ignore_ascii_case(key.name));
                        } else {
                            self.kbd_selected.push(key.name.to_string());
                        }
                    }
                    resp.on_hover_text(hover);
                }

                ui.add_space(8.0);

                /* 已选 (待添加) 与待移除 chips */
                if self.kbd_selected.is_empty() && self.kbd_removals.is_empty() {
                    ui.label(th.hint_text("尚未选择按键 — 点上方键盘开始 (点绿键 = 标记移除)"));
                } else {
                    if !self.kbd_selected.is_empty() {
                        ui.horizontal_wrapped(|ui| {
                            ui.label(th.weak("已选:"));
                            let names = self.kbd_selected.clone();
                            for name in &names {
                                if th
                                    .badge_clickable(
                                        ui,
                                        &format!("{}  ✕", name),
                                        th.accent_text,
                                        th.accent_soft,
                                    )
                                    .clicked()
                                {
                                    self.kbd_selected
                                        .retain(|s| !s.eq_ignore_ascii_case(name));
                                }
                            }
                        });
                    }
                    if !self.kbd_removals.is_empty() {
                        ui.horizontal_wrapped(|ui| {
                            ui.label(th.weak("待移除:"));
                            let names = self.kbd_removals.clone();
                            for name in &names {
                                if th
                                    .badge_clickable(
                                        ui,
                                        &format!("{}  ✕", name),
                                        th.bad,
                                        th.bad_soft,
                                    )
                                    .clicked()
                                {
                                    self.kbd_removals
                                        .retain(|s| !s.eq_ignore_ascii_case(name));
                                }
                            }
                        });
                    }
                }
                ui.add_space(6.0);

                /* 确认 / 取消修改连发 (添加勾选 + 移除标红, 一次生效 / 全部撤销暂存) */
                ui.horizontal(|ui| {
                    let staged = !self.kbd_selected.is_empty() || !self.kbd_removals.is_empty();
                    if ui
                        .add_enabled(staged, th.primary_button("确认修改连发"))
                        .on_disabled_hover_text("先在键盘上点选按键或标记移除")
                        .clicked()
                    {
                        let mut conflicts: Vec<String> = Vec::new();
                        let mut free: Vec<String> = Vec::new();
                        for name in &self.kbd_selected {
                            match key_map_state(&self.config, name) {
                                KeyMapState::SameName => {}
                                KeyMapState::OtherTarget => conflicts.push(name.clone()),
                                KeyMapState::Free => free.push(name.clone()),
                            }
                        }
                        if conflicts.is_empty() {
                            apply_pending_changes_gui(self, &free);
                            self.kbd_selected.clear();
                        } else {
                            self.kbd_pending_free = free;
                            self.kbd_conflicts = Some(conflicts);
                        }
                    }
                    if ui
                        .add_enabled(staged, th.secondary_button("取消修改连发"))
                        .on_disabled_hover_text("当前没有未确认的修改")
                        .clicked()
                    {
                        /* 清空全部暂存: 已选 + 待移除 + 冲突询问 (不碰配置) */
                        self.kbd_selected.clear();
                        self.kbd_removals.clear();
                        self.kbd_pending_free.clear();
                        self.kbd_conflicts = None;
                    }
                    ui.label(th.hint_text(
                        "确认 = 添加已选键的同名连发 + 移除标红键 (覆盖冲突前会先询问); 取消 = 撤销全部未确认修改",
                    ));
                });

                /* 冲突确认 (内联提示框) */
                let conflicts = self.kbd_conflicts.clone();
                if let Some(conflicts) = &conflicts {
                    ui.add_space(6.0);
                    egui::Frame::NONE
                        .fill(th.warn_soft)
                        .corner_radius(egui::CornerRadius::same(8))
                        .inner_margin(egui::Margin::same(10))
                        .show(ui, |ui| {
                            ui.label(
                                egui::RichText::new("⚠ 以下按键已有其他映射, 是否覆盖为同名连发?")
                                    .size(12.5)
                                    .strong()
                                    .color(th.warn),
                            );
                            ui.label(th.hint_text(format!(
                                "冲突按键: {} (覆盖 = 目标改为同名并开启连发)",
                                conflicts.join("、")
                            )));
                            ui.add_space(4.0);
                            ui.horizontal(|ui| {
                                if ui.add(th.primary_button("覆盖并添加")).clicked() {
                                    for name in conflicts {
                                        overwrite_to_same_name_turbo(self, name);
                                    }
                                    apply_pending_changes_gui(self, &self.kbd_pending_free.clone());
                                    self.kbd_selected.clear();
                                    self.kbd_pending_free.clear();
                                    self.kbd_conflicts = None;
                                }
                                if ui.add(th.secondary_button("跳过冲突项")).clicked() {
                                    apply_pending_changes_gui(self, &self.kbd_pending_free.clone());
                                    self.kbd_selected.clear();
                                    self.kbd_pending_free.clear();
                                    self.kbd_conflicts = None;
                                }
                                if ui.add(th.secondary_button("取消")).clicked() {
                                    self.kbd_pending_free.clear();
                                    self.kbd_conflicts = None;
                                }
                            });
                        });
                }
            });
        });
    }
}

/// 落盘 + 热重载 (键盘卡片配置变更后统一走这里)
fn save_and_reload(gui: &mut SorahkGui) {
    let _ = gui.config.save_to_file("Config.toml");
    if let Err(e) = gui.app_state.reload_config(gui.config.clone()) {
        eprintln!("Failed to reload config after keyboard quick change: {e}");
    }
}

/// 构造同名连发映射 (S→S + 连发开, 其余默认)
fn same_name_turbo_mapping(name: &str) -> KeyMapping {
    KeyMapping {
        trigger_key: name.to_string(),
        target_keys: smallvec::SmallVec::from_vec(vec![name.to_string()]),
        interval: None,
        event_duration: None,
        turbo_enabled: true,
        move_speed: 5,
        double_tap_enabled: false,
        double_tap_gap_ms: 50,
        run_enabled: false,
        run_threshold: 80,
        run_recheck: true,
        lock_enabled: false,
        sequence_text: String::new(),
        release_targets: smallvec::SmallVec::new(),
        note: String::new(),
    }
}

/// ★确认修改连发 (纯配置部分): 一次批量生效 = 先移除标红键, 再添加勾选键的同名连发。
/// 返回 (移除数, 添加数)。添加时触发键已被占用 (含本次仍存留的) 则跳过, 不产生重复触发键。
fn apply_pending_changes(
    config: &mut AppConfig,
    removals: &[String],
    adds: &[String],
) -> (usize, usize) {
    let mut removed = 0usize;
    for name in removals {
        if remove_same_name_mapping(config, name).is_some() {
            removed += 1;
        }
    }
    let mut added = 0usize;
    for name in adds {
        if config
            .mappings
            .iter()
            .any(|m| m.trigger_key.eq_ignore_ascii_case(name))
        {
            continue;
        }
        config.mappings.push(same_name_turbo_mapping(name));
        added += 1;
    }
    (removed, added)
}

/// ★确认修改连发 (GUI 封装): 应用暂存的移除+添加并落盘热重载
fn apply_pending_changes_gui(gui: &mut SorahkGui, adds_free: &[String]) {
    let removals = std::mem::take(&mut gui.kbd_removals);
    let (removed, added) = apply_pending_changes(&mut gui.config, &removals, adds_free);
    if removed > 0 || added > 0 {
        save_and_reload(gui);
    }
}

/// 把既有映射覆盖为同名连发 (S→X → S→S + 连发)
fn overwrite_to_same_name_turbo(gui: &mut SorahkGui, name: &str) {
    if let Some(m) = gui
        .config
        .mappings
        .iter_mut()
        .find(|m| m.trigger_key.eq_ignore_ascii_case(name))
    {
        m.target_keys = smallvec::SmallVec::from_vec(vec![name.to_string()]);
        m.turbo_enabled = true;
        m.sequence_text = String::new();
    }
}

/// ★v24.33 移除触发键为 name 的映射 (绿键标记的删除在确认时走这里)。
/// 大小写不敏感; 找不到返回 None。纯配置操作不落盘 — 调用方负责 save + reload。
fn remove_same_name_mapping(config: &mut AppConfig, name: &str) -> Option<(usize, KeyMapping)> {
    let idx = config
        .mappings
        .iter()
        .position(|m| m.trigger_key.eq_ignore_ascii_case(name))?;
    Some((idx, config.mappings.remove(idx)))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 从标签串里取 key="value" 属性值 (value 解析为 f32)
    fn attr(tag: &str, key: &str) -> Option<f32> {
        let p = tag.find(key)? + key.len();
        let v = &tag[p..];
        let e = v.find('"')?;
        v[..e].parse().ok()
    }

    /// 解析 SVG 中每个 <g id="X"> 内第一个 <rect> 的几何
    fn parse_svg_geometry(svg: &str) -> Vec<(&str, f32, f32, f32, f32)> {
        let mut out = Vec::new();
        let mut rest = svg;
        while let Some(i) = rest.find("<g id=\"") {
            let after_id = &rest[i + 7..];
            let Some(id_end) = after_id.find('"') else { break };
            let id = &after_id[..id_end];
            let body_end = after_id.find("</g>").unwrap_or(after_id.len());
            let body = &after_id[..body_end];
            if let Some(r) = body.find("<rect ") {
                let tag = &body[r..];
                let tag = &tag[..tag.find('>').unwrap_or(tag.len())];
                if let (Some(x), Some(y), Some(w), Some(h)) = (
                    attr(tag, "x=\""),
                    attr(tag, " y=\""),
                    attr(tag, "width=\""),
                    attr(tag, "height=\""),
                ) {
                    out.push((id, x, y, w, h));
                }
            }
            rest = &after_id[body_end..];
        }
        out
    }

    /// ★v24.33 回归守卫: KEYS 表坐标必须与 SVG 实际 rect 几何一致。
    /// 历史 bug: 生成时浮点被格式化成 1 位有效数字 (2e+02), 102 键热区全部错位
    /// (点击 G 选中 H)。渲染把图像与热区经同一 rect 线性映射, 坐标一致 ⇒ 屏幕对齐。
    #[test]
    fn keys_table_matches_svg_geometry() {
        for (path, svg) in [
            ("dark", include_str!("../../resources/keyboard.svg")),
            ("light", include_str!("../../resources/keyboard-light.svg")),
        ] {
            let geo = parse_svg_geometry(svg);
            assert_eq!(geo.len(), KEYS.len(), "{}: SVG 键数 {} != 表条目 {}", path, geo.len(), KEYS.len());
            for k in KEYS {
                let hit = geo
                    .iter()
                    .find(|(id, ..)| id.eq_ignore_ascii_case(k.name))
                    .unwrap_or_else(|| panic!("{}: SVG 缺少键 {}", path, k.name));
                let (_, x, y, w, h) = *hit;
                assert!(
                    (k.x - x).abs() < 0.05 && (k.y - y).abs() < 0.05
                        && (k.w - w).abs() < 0.05 && (k.h - h).abs() < 0.05,
                    "{}: 键 {} 表坐标 ({},{},{},{}) != SVG ({},{},{},{})",
                    path, k.name, k.x, k.y, k.w, k.h, x, y, w, h
                );
            }
        }
    }

    fn km(trigger: &str) -> KeyMapping {
        KeyMapping {
            trigger_key: trigger.to_string(),
            target_keys: smallvec::SmallVec::from_vec(vec![trigger.to_string()]),
            interval: None,
            event_duration: None,
            turbo_enabled: true,
            move_speed: 5,
            double_tap_enabled: false,
            double_tap_gap_ms: 50,
            run_enabled: false,
            run_threshold: 80,
            run_recheck: true,
            lock_enabled: false,
            sequence_text: String::new(),
            release_targets: smallvec::SmallVec::new(),
            note: String::new(),
        }
    }

    /// ★v24.33 确认修改连发: 移除 + 添加一次批量生效; 已占用触发键跳过
    #[test]
    fn apply_pending_changes_batches() {
        let mut cfg = AppConfig::default();
        cfg.mappings.clear(); // 出厂默认自带 Q→Q, 清空后按已知顺序构造
        cfg.mappings.push(km("S"));
        cfg.mappings.push(km("D"));

        /* 移除 S + 添加 H; D 已占用被跳过 (大小写不敏感) */
        let (removed, added) = apply_pending_changes(
            &mut cfg,
            &["s".to_string()],
            &["H".to_string(), "D".to_string()],
        );
        assert_eq!((removed, added), (1, 1));
        assert!(cfg.mappings.iter().all(|m| m.trigger_key != "S"));
        let h = cfg
            .mappings
            .iter()
            .find(|m| m.trigger_key == "H")
            .expect("H 应被添加");
        assert!(h.turbo_enabled);
        assert_eq!(h.target_keys[0], "H");

        /* 移除不存在的键: 计 0 不 panic; 无变更 */
        let (removed, added) = apply_pending_changes(&mut cfg, &["Z".to_string()], &[]);
        assert_eq!((removed, added), (0, 0));
        assert_eq!(cfg.mappings.len(), 2); // D + H
    }
}
